### ISSUE TITLE
Include indi_raspistill driver

### ISSUE THREAD

**Issue by philippebourcier** [rlancaste/AstroPi3#15]
The new Official HQ Camera from Raspberry Pi is probably going to be the next big thing in Pi-based astrophotography.

Hopefully, @lboclboc is already writing an INDI driver for it : https://github.com/lboclboc/indi_raspistill

This is probably something worse including in AstroPi3...

**Comment by rlancaste** [comment]
Sounds very cool!  Wouldn't this be something for INDI 3rd Party?

**Comment by rlancaste** [comment]
If we get it in there, then it will automatically get included in AstroPi3 and it will be included in most other builds too.

https://github.com/indilib/indi-3rdparty

**Comment by lboclboc** [comment]
I'd be happy to have it included. How does one go about?
It works, but need more settable parameters right now but I plan to add that shortly.

**Comment by rlancaste** [comment]
I will send a message to Jasem.  The easiest way would be for you to clone the 3rd party repo, add your driver, and submit a pull request.

**Comment by knro** [comment]
@lboclboc Great to hear. Once the driver is stable and ready, please submit a Pull-Request to [INDI 3rdparty](https://github.com/indilib/indi-3rdparty) repository.

**Comment by lboclboc** [comment]
Will do, thanks

**Comment by rlancaste** [comment]
I just received a High Quality Raspberry Pi camera that I ordered.  It came in the mail yesterday.  I tried your driver as well as INDI Webcam and INDI V4L2.  All 3 did work with the camera.  I found that to run the INDI Raspbistill driver, I definitely had to do updates before it would work, but once I did so, it worked well, but right now has limited capabilities and I had to copy and paste the built driver in order to use it (there was no install option in the cmakeLists)

**Comment by rlancaste** [comment]
One significant note:  When I ran the Raspbistill driver, the resolution was 4056 x 3040.  But when I ran it using the other drivers it was MUCH reduced to 640 x 480.  I am not sure why, but it probably is related to V4L2, but I will look into it.  On the other had, the download times were MUCH longer with the raspbistill driver.  I assume this is because it was downloading much bigger images.

**Comment by lboclboc** [comment]
> I just received a High Quality Raspberry Pi camera that I ordered. It came in the mail yesterday. I tried your driver as well as INDI Webcam and INDI V4L2. All 3 did work with the camera. I found that to run the INDI Raspbistill driver, I definitely had to do updates before it would work, but once I did so, it worked well, but right now has limited capabilities and I had to copy and paste the built driver in order to use it (there was no install option in the cmakeLists)

True, my next step is to create a pull request in indi-3rdparty. There I will include install and xml-files. About the resolution, from what I understant the resolution is max 1080p via the video-port that I think v4l is using. Then its also only 8 bit. The raw image is in bayerformat 4056x3040 and its 12 bit (actually stored as 16bit) so its about 26 times larger than you 640x480 so yes it would take longer time. I see most of the time is actually during the transfer from the indi-driver to the client. Perhaps investigating the websock method would be worth while here.
About functionality, what additionally  functions would you need most from now on? I was thinking bit binning would be nice. The camera does support it in hardware also.
Regards, Lars

**Comment by rlancaste** [comment]
I think I can close this now because It looks like you have included it in 3rd Party now
