### ISSUE TITLE
dpkg lock at the beginning

### ISSUE THREAD

**Issue by Kuehni84** [rlancaste/AstroPi3#5]
Hello,
i want to start the install script (sudo ./setupAstroPi3.sh), but i get the following error message
"dpkg is currently locked, meaning another program is either checking for updates or is currently updating the system.
Please wait for a few minutes or quit the other process and run this script again.  Exiting now."

I have tried some tshoot mentioned at google but nothing helped.

At this time i can't install AstroPi3. :(

I have the latest version of Ubuntu Mate (Ubuntu MATE 18.04.2 (Bionic)) and tried the 32Bit & 64Bit version.

i need some help.

thank you very much.

**Comment by dragonlost** [comment]
for correct this error need desactivate auto update on "software and update menu" and reboot. dpkg is block by auto update at start.

**Comment by Kuehni84** [comment]
Hi,

thank you for your help. But to deactivate the automatic updates didn't help.

Any other ideas?

Greetings

**Comment by Kuehni84** [comment]
I tried Raspbian too. Same message occurs. Raspbian has no automatic update function.

weird...

**Comment by Kuehni84** [comment]
Hm,

i had a workaround. I removed the dpkg check in the install script.
But that's not how it should be.
So i'm happy for any further ideas.
Greetings

**Comment by starhopper-de** [comment]
Hello,
yesterday I installed my new RasperryPi3B+ with Ubuntu MATE 18.04.2 and your script. I ran into the same issue: "DPKG locked". I decided to comment the script lines out, not knowing this thread.
The further install worked seamless. I lacks the desktop icon with the wireless settings. 

I can say that the performance with the new RasperryPI3B+ is much faster in comparison with the PI3B. More than the written data suggests. I is worth the upgrade.

**Comment by rlancaste** [comment]
Sorry for my slow response.  The dpkg lock issue is that sometimes ubuntu mate likes to install "unattended upgrades" in the background and it doesn't ask you before doing it.  Because of this, sometimes you cannot run commands like "sudo apt-get install" or "sudo apt-get upgrade" until it is finished.  So I had added the check to let you know about the issue so that you don't try to run the scripts until it is done its thing.  I have tried different ways to get around this, but the recommendations I have seen so far say that is not a good idea and you should wait until dpkg is finished.

**Comment by rlancaste** [comment]
one possibility is to set the pi to not install "unattended upgrades" in the setting somewhere.  I haven't looked into how to to this programmatically, but I think it might work in the GUI.  I think I tried this on mine last year and it worked.

**Comment by starhopper-de** [comment]
`Sorry for my slow response. The dpkg lock issue is that sometimes ubuntu mate likes to install "unattended upgrades" in the background and it doesn't ask you before doing it. Because of this, sometimes you cannot run commands like "sudo apt-get install" or "sudo apt-get upgrade" until it is finished. `
That was my first idea too, but I could a "sudo apt-get install" during that time. So I decided to comment it out.
Thomas

**Comment by rlancaste** [comment]
It is possible that they changed that about Ubuntu.  I just found that I was often getting annoyed at my script stopping partway through due to dpkg not being ready. So I put a check on it at the beginning.  Also I was thinking about the distribution of the script, a user who is not as familiar with the system might wonder why it is not working.  This way there is at least a check and a warning.  If you want to disable it , that’s fine too

**Comment by rlancaste** [comment]
I have now eliminated the dpkg check from the script.  It was having some false positives.  I instead removed the package that caused the need for the check in the first place
